# Generated by Django 4.2.9 on 2024-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="adminuser", options={},),
        migrations.AlterModelManagers(name="adminuser", managers=[],),
        migrations.RemoveField(model_name="adminuser", name="date_joined",),
        migrations.RemoveField(model_name="adminuser", name="email",),
        migrations.RemoveField(model_name="adminuser", name="first_name",),
        migrations.RemoveField(model_name="adminuser", name="groups",),
        migrations.RemoveField(model_name="adminuser", name="is_active",),
        migrations.RemoveField(model_name="adminuser", name="is_staff",),
        migrations.RemoveField(model_name="adminuser", name="is_superuser",),
        migrations.RemoveField(model_name="adminuser", name="last_login",),
        migrations.RemoveField(model_name="adminuser", name="last_name",),
        migrations.RemoveField(model_name="adminuser", name="user_permissions",),
        migrations.RemoveField(model_name="adminuser", name="username",),
        migrations.AddField(
            model_name="adminuser",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="password",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
