# Generated by Django 4.2.9 on 2024-02-07 10:20

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "volunteers",
            "0002_alter_adminuser_options_alter_adminuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.RemoveField(model_name="adminuser", name="name",),
        migrations.AddField(
            model_name="adminuser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(
                default="admin@change.me", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="adminuser_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="adminuser_permissions", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="username",
            field=models.CharField(
                default="admin_username", max_length=150, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="password",
            field=models.CharField(default="admin_password", max_length=128),
        ),
    ]
