# Generated by Django 4.2.9 on 2024-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "volunteers",
            "0003_alter_adminuser_options_alter_adminuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="anonymoususer", name="name",),
        migrations.AddField(
            model_name="anonymoususer",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="anonymoususer",
            name="password",
            field=models.CharField(default="anonymous_password", max_length=128),
        ),
        migrations.AddField(
            model_name="anonymoususer",
            name="username",
            field=models.CharField(
                default="anonymous_username", max_length=150, unique=True
            ),
        ),
    ]
