# Generated by Django 4.2.9 on 2024-02-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0005_participant_delete_anonymoususer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="password",
            field=models.CharField(default="participant_password", max_length=128),
        ),
    ]
