# Generated by Django 4.2.9 on 2024-02-07 18:24

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0006_alter_participant_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="participant",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AddField(
            model_name="participant",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(
                default="admin@change.me", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="participant",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="participant",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
