# Generated by Django 4.2.9 on 2024-02-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "volunteers",
            "0007_alter_participant_options_alter_participant_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
    ]
