# Generated by Django 4.2.9 on 2024-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0009_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="end_date", field=models.DateTimeField(null=True),
        ),
    ]
