# Generated by Django 4.2.9 on 2024-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0012_choice_question_survey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey", name="admin", field=models.CharField(max_length=200),
        ),
    ]
