# Generated by Django 4.2.9 on 2024-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0013_alter_survey_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="survey_id",
            field=models.IntegerField(default=0),
        ),
    ]
