# Generated by Django 4.2.9 on 2024-02-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0014_question_survey_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="choices",),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="volunteers.question",
            ),
        ),
    ]
