# Generated by Django 4.2.9 on 2024-02-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0016_alter_choice_question"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="survey_id",),
        migrations.RemoveField(model_name="survey", name="questions",),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="volunteers.survey",
            ),
        ),
    ]
