# Generated by Django 4.2.9 on 2024-02-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "volunteers",
            "0017_remove_question_survey_id_remove_survey_questions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="choice", name="question",),
        migrations.RemoveField(model_name="question", name="survey",),
        migrations.AddField(
            model_name="question",
            name="choices",
            field=models.ManyToManyField(blank=True, to="volunteers.choice"),
        ),
        migrations.AddField(
            model_name="question",
            name="survey_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="survey",
            name="questions",
            field=models.ManyToManyField(to="volunteers.question"),
        ),
    ]
