# Generated by Django 4.2.9 on 2024-02-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0019_remove_question_survey_id_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer", name="user", field=models.CharField(max_length=200),
        ),
    ]
