# Generated by Django 4.2.9 on 2024-02-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0020_alter_answer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
