# Generated by Django 4.2.9 on 2024-02-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0021_alter_answer_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="volunteers.participant"
            ),
        ),
    ]
